apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: terraform-labs
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: autoscaling
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Github-Arun-Repo/terraform-labs.git
    targetRevision: main
    path: k8s/karpenter/karpenter
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
