apiVersion: v2
name: dynamic-jenkins
description: Wrapper chart to deploy Jenkins with dynamic Kubernetes agents on EKS
type: application
version: 0.1.0
appVersion: "2.492.3"
dependencies:
  - name: jenkins
    version: ">=5.0.0 <6.0.0"
    repository: https://charts.jenkins.io