{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "document-processing-service.fullname" . }}-ingress
  labels:
    {{- include "document-processing-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "document-processing-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  {{- toYaml .Values.networkPolicy.allowedIngressNamespaces | nindent 18 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.prometheusNamespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
{{- end }}
