apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-cpu-memory-requests-limits
  annotations:
    policies.kyverno.io/title: Require Resources
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: {{ .Values.policyValidationFailureAction }}
  background: true
  rules:
    - name: require-container-resources
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                {{- toYaml .Values.excludedNamespaces | nindent 16 }}
      validate:
        message: Containers must define CPU and memory requests and limits.
        foreach:
          - list: request.object.spec.containers
            pattern:
              resources:
                requests:
                  cpu: "?*"
                  memory: "?*"
                limits:
                  cpu: "?*"
                  memory: "?*"
